replicaCount: 1

# Configuración de la imagen del contenedor
image:
  repository: juaandaaniel/mi-api-python
  pullPolicy: IfNotPresent
  tag: "f40381a02c3cb8828a9b88352dccd41df02089ae"

# Variables de entorno para la aplicación
env:
  appEnv: "Desarrollo"

# Configuración del servicio de Kubernetes
service:
  type: ClusterIP
  port: 80
  targetPort: 8000