replicaCount: 1

# Configuración de la imagen del contenedor
image:
  repository: juaandaaniel/mi-api-python
  pullPolicy: IfNotPresent
  tag: "7c5075e2af5f39eeb1981b8127a006a65b0ced2a"

# Variables de entorno para la aplicación
env:
  appEnv: "Desarrollo"

# Configuración del servicio de Kubernetes
service:
  type: ClusterIP
  port: 80
  targetPort: 8000